USE vsl_learning;
INSERT INTO lesson_contents (id, lesson_id, type, title, order_index) VALUES (3, 20, 'grid', 'Kí hiệu về bản thân', 1);

INSERT INTO content_items (content_id, title, description, image_url, keywords, order_index) VALUES
(3,'Bé trai','Tay phải khép, lòng bàn tay úp, đặt trước ngực, đưa tay xuống dưới. Tay phải giống chữ U, đặt chạm vào cằm, gập ngón tay xuống.','/images/pages/page0080_img01.png','bé trai,trẻ em,giới tính',1),
(3,'Bé gái','Tay phải khép, lòng bàn tay úp, đặt trước ngực, đưa tay xuống dưới. Ngón trỏ và ngón cái nắm nhẹ vào tai phải.','/images/pages/page0080_img01.png','bé gái,trẻ em,giới tính',2),
(3,'Cao','Tay phải khép, lòng bàn tay úp, đặt trước ngực, di chuyển tay lên trên.','/images/pages/page0080_img01.png','cao,chiều cao',3),
(3,'Thấp','Tay phải khép, lòng bàn tay úp, đặt trước ngực, di chuyển tay xuống dưới.','/images/pages/page0080_img01.png','thấp,chiều cao',4),
(3,'Gầy','Hai tay nắm, ngón cái mở ra hướng lên, đặt ở hai bên, di chuyển cả hai tay vào gần nhau.','/images/pages/page0081_img01.png','gầy,thể trạng',5),
(3,'Béo','Hai tay mở, lòng bàn tay hướng vào nhau, đặt gần hai bên má, di chuyển cả hai tay sang hai bên.','/images/pages/page0081_img01.png','béo,thể trạng',6),
(3,'Đầu','Tay phải khép, đặt gần đầu, di chuyển tay chạm vào đầu.','/images/pages/page0081_img01.png','đầu,cơ thể',7),
(3,'Tóc','Tay phải mở, ngón cái và ngón trỏ nắm nhẹ vào tóc.','/images/pages/page0081_img01.png','tóc,cơ thể',8),
(3,'Mắt','Tay phải giống số 1, đặt chạm đầu ngón trỏ vào đuôi mắt phải.','/images/pages/page0082_img01.png','mắt,cơ thể',9),
(3,'Mũi','Tay phải giống số 1, đặt chạm đầu ngón trỏ vào mũi.','/images/pages/page0082_img01.png','mũi,cơ thể',10),
(3,'Miệng','Tay phải giống số 1, đặt chạm đầu ngón trỏ vào miệng.','/images/pages/page0082_img01.png','miệng,cơ thể',11),
(3,'Tai','Tay phải giống số 1, đặt chạm đầu ngón trỏ vào tai.','/images/pages/page0082_img01.png','tai,cơ thể',12),
(3,'Răng','Tay phải giống số 1, đặt chạm vào răng.','/images/pages/page0083_img01.png','răng,cơ thể',13),
(3,'Lưỡi','Tay phải mở, ngón cái và ngón trỏ đặt hai bên miệng, lè lưỡi ra.','/images/pages/page0083_img01.png','lưỡi,cơ thể',14),
(3,'Cổ','Tay phải khép, đặt chạm vào cổ.','/images/pages/page0083_img01.png','cổ,cơ thể',15),
(3,'Vai','Tay phải khép, đặt chạm vào vai.','/images/pages/page0083_img01.png','vai,cơ thể',16),
(3,'Ngực','Tay phải khép, đặt chạm vào ngực.','/images/pages/page0084_img01.png','ngực,cơ thể',17),
(3,'Bụng','Tay phải khép, đặt chạm vào bụng.','/images/pages/page0084_img01.png','bụng,cơ thể',18),
(3,'Lưng','Tay phải khép, đưa ra sau đặt chạm vào lưng.','/images/pages/page0084_img01.png','lưng,cơ thể',19),
(3,'Tay','Tay trái duỗi thẳng, tay phải nắm vào cánh tay trái.','/images/pages/page0084_img01.png','tay,cơ thể',20),
(3,'Chân','Tay phải khép, đặt chạm vào đùi, di chuyển xuống chân.','/images/pages/page0085_img01.png','chân,cơ thể',21),
(3,'Ngón tay','Tay trái mở, tay phải nắm lần lượt vào từng ngón tay trái.','/images/pages/page0085_img01.png','ngón tay,cơ thể',22),
(3,'Da','Tay phải nắm, ngón cái và ngón trỏ véo nhẹ da mu bàn tay trái.','/images/pages/page0085_img01.png','da,cơ thể',23),
(3,'Xương','Hai tay bắt chéo trước ngực, các ngón tay đặt lên vai đối diện.','/images/pages/page0085_img01.png','xương,cơ thể',24),
(3,'Nam','Tay phải khép, hơi khum lại, đặt chạm các đầu ngón tay vào cằm.','/images/pages/page0086_img01.png','nam,giới tính',25),
(3,'Nữ','Tay phải nắm, ngón cái và ngón trỏ mở ra, nắm nhẹ vào tai.','/images/pages/page0086_img01.png','nữ,giới tính',26),
(3,'Trẻ em','Tay phải khép, lòng bàn tay úp, đặt trước ngực, đưa tay xuống dưới.','/images/pages/page0086_img01.png','trẻ em,tuổi',27),
(3,'Người lớn','Tay phải khép, lòng bàn tay úp, đặt trước ngực, đưa tay lên trên.','/images/pages/page0086_img01.png','người lớn,tuổi',28),
(3,'Người già','Tay phải giống chữ C, đặt dưới cằm, đưa tay xuống đồng thời nắm lại. Tay cong giống cầm gậy.','/images/pages/page0087_img01.png','người già,tuổi',29),
(3,'Người điếc','1. Tay phải giống số 1, đặt chạm vào tai. 2. Tay phải nắm, lòng bàn tay úp, đặt trước miệng.','/images/pages/page0087_img01.png','người điếc,khiếm thính',30),
(3,'Người nghe','1. Tay phải giống số 1, đặt chạm vào tai. 2. Tay phải mở, lòng bàn tay ngửa, đặt trước miệng.','/images/pages/page0087_img01.png','người nghe,thính giác',31),
(3,'Áo','Tay phải nắm, ngón cái và ngón trỏ mở ra nắm nhẹ vào áo và kéo nhẹ lên.','/images/pages/page0088_img01.png','áo,trang phục',32),
(3,'Áo dài','1. Nắm nhẹ vào áo kéo lên. 2. Hai tay khép, lòng bàn tay úp, đặt sát hông, di chuyển hai tay xuống dưới.','/images/pages/page0088_img01.png','áo dài,trang phục',33),
(3,'Áo khoác','1. Nắm nhẹ vào áo kéo lên. 2. Hai tay nắm, đặt trước ngực, làm động tác kéo khóa.','/images/pages/page0088_img01.png','áo khoác,trang phục',34),
(3,'Áo mưa','1. Nắm nhẹ vào áo kéo lên. 2. Hai tay mở xoè, lòng bàn tay úp, đặt sát ngực, di chuyển hai tay xuống.','/images/pages/page0088_img01.png','áo mưa,trang phục',35),
(3,'Quần âu','1. Tay phải nắm, ngón cái và ngón trỏ mở ra nắm nhẹ vào quần kéo lên. 2. Ngón cái và ngón trỏ mở ra, đặt gần bên cạnh mũi, đưa tay xuống chạm hai ngón.','/images/pages/page0090_img01.png','quần âu,trang phục',36),
(3,'Quần bò','1. Nắm nhẹ vào quần kéo lên. 2. Hai tay giống chữ N, lòng bàn tay hướng vào nhau, đặt song song trước ngực, gập cổ tay phải lên, gập cổ tay trái xuống.','/images/pages/page0090_img01.png','quần bò,jeans,trang phục',37),
(3,'Quần soóc','Tay phải khép lại, lòng bàn tay ngửa, đặt áp vào đùi, đưa tay sang phải.','/images/pages/page0090_img01.png','quần soóc,shorts,trang phục',38),
(3,'Guốc','1. Tay trái khum, lòng bàn tay ngửa, đặt trước ngực. Tay phải khép, lòng bàn tay úp, đưa vào trong tay trái. 2. Tay phải mở xoè, di chuyển mạnh tay xuống chạm vào mu bàn tay trái.','/images/pages/page0090_img01.png','guốc,giày dép',39),
(3,'Yếm','1. Hai tay nắm, lòng bàn tay úp, đặt gần nhau trước cổ, di chuyển theo đường vòng cung ra sau gáy. 2. Hai tay mở xoè, đặt sát ngực, di chuyển hai tay xuống.','/images/pages/page0091_img01.png','yếm,trang phục',40),
(3,'Giày','1. Tay trái khép khum, lòng bàn tay ngửa. Tay phải khép úp, đưa vào trong tay trái. 2. Hai tay làm giống động tác buộc dây giày.','/images/pages/page0091_img01.png','giày,giày dép',41),
(3,'Dép','Tay trái khép khum, lòng bàn tay ngửa, đặt trước ngực. Tay phải khép úp, đưa các đầu ngón tay vào trong lòng bàn tay trái.','/images/pages/page0091_img01.png','dép,giày dép',42),
(3,'Tất','Tay trái giống chữ V, lòng bàn tay úp. Tay phải nắm, ngón trỏ và ngón cái chụm, đặt chạm vào đầu ngón trỏ tay trái, di chuyển dọc lên trên.','/images/pages/page0091_img01.png','tất,vớ,phụ kiện',43),
(3,'Găng tay','Tay trái khép, lòng bàn tay hướng vào trong. Tay phải khép, nắm vào đầu các ngón tay trái, vuốt dọc xuống cổ tay đồng thời các ngón tay trái xoè ra.','/images/pages/page0092_img01.png','găng tay,phụ kiện',44),
(3,'Nón','Hai tay khép, lòng bàn tay hướng vào nhau, đặt gần hai bên trán, đưa đồng thời hai tay xuống dưới và về hai phía.','/images/pages/page0092_img01.png','nón,mũ,phụ kiện',45),
(3,'Mũ','Tay phải khép khum, lòng bàn tay úp, đặt áp vào đỉnh đầu.','/images/pages/page0092_img01.png','mũ,phụ kiện',46),
(3,'Mũ lưỡi trai','Tay phải khép khum, đặt gần trán, đưa tay về phía trước đồng thời chụm các ngón tay lại.','/images/pages/page0092_img01.png','mũ lưỡi trai,phụ kiện',47),
(3,'Kính','Tay phải nắm, ngón trỏ và ngón cái cong lại giống chữ C, đặt áp vào mắt phải.','/images/pages/page0093_img01.png','kính,phụ kiện',48),
(3,'Hoa tai','1. Tay phải mở, ngón trỏ và ngón cái nắm nhẹ vào tai phải. 2. Tay phải giống chữ O, đặt bên phải ngang mặt, mở xoè các ngón tay ra.','/images/pages/page0093_img01.png','hoa tai,bông tai,phụ kiện',49),
(3,'Lược','Tay phải mở khum, đặt chạm các đầu ngón tay vào bên phải đầu, di chuyển tay xuống dưới (2 lần).','/images/pages/page0093_img01.png','lược,phụ kiện',50),
(3,'Cặp tóc','Tay phải nắm, ngón trỏ và ngón cái duỗi thẳng, đặt chạm vào bên phải đầu, di chuyển tay lên trên đồng thời ngón trỏ ngón cái chụm lại.','/images/pages/page0093_img01.png','cặp tóc,phụ kiện',51),
(3,'Bàn chải','1. Tay trái giống số 1, đặt trước ngực. Tay phải nắm, ngón cái và ngón trỏ chụm, đặt chạm vào gốc ngón trỏ tay trái, di chuyển ra đầu ngón trỏ. 2. Tay phải giống số 1, đặt ngang miệng, di chuyển sang trái rồi sang phải.','/images/pages/page0094_img01.png','bàn chải,vệ sinh',52),
(3,'Khăn mặt','1. Hai tay giống số 1, lòng bàn tay úp, đặt song song trước ngực, di chuyển đồng thời theo đường hình chữ nhật. 2. Tay phải khép, đặt gần trán, di chuyển một vòng quanh mặt.','/images/pages/page0094_img01.png','khăn mặt,vệ sinh',53),
(3,'Chào','Tay phải khép, lòng bàn tay hướng về phía trước, đặt bên phải ngang tầm mặt, đưa nhẹ tay sang hai bên (1-2 lần).','/images/pages/page0094_img01.png','chào,giao tiếp',54),
(3,'Bạn','Hai tay khép, ngón cái mở ra, lòng bàn tay hướng vào nhau, đặt trước ngực, tay phải ở trên tay trái, bắt hai tay vào nhau.','/images/pages/page0094_img01.png','bạn,giao tiếp',55),
(3,'Tuổi','Tay trái nắm, lòng bàn tay hướng vào trong, đặt trước ngực. Tay phải khép hơi khum, đặt trên tay trái, xoay cổ tay một vòng từ ngoài vào trong rồi nắm tay lại chạm vào tay trái.','/images/pages/page0095_img01.png','tuổi,giao tiếp',56),
(3,'Tên là gì?','1. Hai tay giống số 1, đặt chéo ngón trỏ phải bên trên ngón trỏ trái, trước ngực, đưa ngón trỏ phải vào ngón trỏ trái (2 lần). 2. Tay phải giống số 1, đặt trước ngực phải, lắc cổ tay qua lại.','/images/pages/page0095_img01.png','tên,hỏi tên,giao tiếp',57),
(3,'Bao nhiêu?','Tay phải nắm, lòng bàn tay ngửa, đặt trước ngực, giữ nguyên cánh tay, mở xoè bàn tay ra (2 lần).','/images/pages/page0095_img01.png','bao nhiêu,câu hỏi,giao tiếp',58),
(3,'Xin lỗi','Tay trái khép lòng bàn tay ngửa, đặt trước ngực. Tay phải khép úp, đặt các đầu ngón tay vào lòng bàn tay trái, đưa tay dọc trong lòng bàn tay trái (2-3 lần).','/images/pages/page0095_img01.png','xin lỗi,giao tiếp',59),
(3,'Xin phép','Tay phải khép, lòng bàn tay ngửa, đặt trước ngực, di chuyển tay áp vào giữa ngực.','/images/pages/page0096_img01.png','xin phép,giao tiếp',60),
(3,'Ở đâu?','Hai tay nắm, ngón cái duỗi thẳng hướng xuống dưới, đặt trước ngực, đầu ngón cái tay phải đặt chéo trên đầu ngón cái tay trái, đưa nhẹ tay xuống dưới, sau đó đưa hai tay về hai phía đồng thời mở xoè ra.','/images/pages/page0096_img01.png','ở đâu,câu hỏi,giao tiếp',61),
(3,'Thế nào?','Hai tay mở, lòng bàn tay úp, đặt song song trước ngực, đưa nhẹ cả hai tay lên trên và về hai phía, đồng thời mở xoè các ngón tay ra.','/images/pages/page0096_img01.png','thế nào,câu hỏi,giao tiếp',62),
(3,'Vui','Hai tay khép, lòng bàn tay hướng vào trong, đầu ngón tay chạm vào nhau, đặt sát ngực, đưa nhẹ đồng thời cả hai tay lên trên và về hai bên (2 lần).','/images/pages/page0096_img01.png','vui,cảm xúc',63),
(3,'Buồn','Tay phải nắm, lòng bàn tay hướng vào trong, đặt áp vào giữa ngực, đưa tay phải xoay tròn theo chiều kim đồng hồ.','/images/pages/page0097_img01.png','buồn,cảm xúc',64),
(3,'Làm gì?','1. Hai tay nắm, đặt trước ngực, tay phải đặt trên tay trái, di chuyển tay phải lên-xuống chạm vào tay trái (2 lần). 2. Tay phải giống số 1, đặt trước ngực, lắc cổ tay sang hai bên.','/images/pages/page0097_img01.png','làm gì,câu hỏi,giao tiếp',65),
(3,'Khoẻ','Hai tay nắm, lòng bàn tay hướng vào nhau, đặt ở hai bên ngang tầm vai, gập mạnh đồng thời cả hai tay vào trong và xuống dưới.','/images/pages/page0097_img01.png','khoẻ,sức khoẻ',66),
(3,'Yếu','Hai tay giống chữ Y, lòng bàn tay úp, đặt song song trước ngực, di chuyển đồng thời hai tay theo đường vòng cung từ ngoài vào trong, đồng thời khuôn mặt thể hiện sự mệt mỏi.','/images/pages/page0097_img01.png','yếu,sức khoẻ',67),
(3,'Mệt','Tay phải mở xoè, lòng bàn tay hướng vào trong, đặt áp vào giữa ngực, đưa nhẹ tay xuống dưới 1-2 lần.','/images/pages/page0098_img01.png','mệt,sức khoẻ',68),
(3,'Màu sắc','1. Tay phải giống chữ M, đặt trước ngực, lắc cổ tay về bên phải. 2. Hai tay giống số 1, đặt gần nhau trước ngực, di chuyển đồng thời cả hai tay sang hai bên (2-3 lần).','/images/pages/page0098_img01.png','màu sắc,màu',69),
(3,'Màu đen','1. Tay phải giống chữ M, lắc cổ tay về bên phải. 2. Tay phải giống số 1, đặt chạm vào đầu bên phải, sau đó đưa tay xuống dưới.','/images/pages/page0098_img01.png','màu đen,đen,màu sắc',70),
(3,'Màu đỏ','1. Tay phải giống chữ M, lắc cổ tay về bên phải. 2. Tay phải giống số 1, đặt áp vào giữa miệng, đưa tay xuống dưới.','/images/pages/page0098_img01.png','màu đỏ,đỏ,màu sắc',71),
(3,'Màu xanh','1. Tay phải giống chữ M, lắc cổ tay về bên phải. 2. Tay phải giống chữ X, đặt trước ngực, lắc cổ tay sang hai bên (2-3 lần).','/images/pages/page0099_img01.png','màu xanh,xanh,màu sắc',72),
(3,'Màu nâu','1. Tay phải giống chữ M, lắc cổ tay về bên phải. 2. Tay phải giống chữ N, đặt trước ngực, lắc cổ tay sang phải.','/images/pages/page0099_img01.png','màu nâu,nâu,màu sắc',73),
(3,'Màu trắng','1. Tay phải giống chữ M, lắc cổ tay về bên phải. 2. Tay phải giống chữ N, đặt chạm vào cánh tay trái, đưa nhẹ tay lên trên.','/images/pages/page0099_img01.png','màu trắng,trắng,màu sắc',74),
(3,'Màu hồng','1. Tay phải giống chữ M, lắc cổ tay về bên phải. 2. Tay phải giống chữ H, đặt sát má phải, đưa tay theo vòng tròn từ ngoài vào trong.','/images/pages/page0099_img01.png','màu hồng,hồng,màu sắc',75),
(3,'Màu vàng','1. Tay phải giống chữ M, lắc cổ tay về bên phải. 2. Tay phải giống chữ V, đặt trước ngực, lắc cổ tay.','/images/pages/page0100_img01.png','màu vàng,vàng,màu sắc',76),
(3,'Màu tím','1. Tay phải giống chữ M, lắc cổ tay về bên phải. 2. Tay phải giống chữ T, đặt trước ngực, lắc cổ tay.','/images/pages/page0100_img01.png','màu tím,tím,màu sắc',77);
