USE vsl_learning;

-- Extra items for Gia dinh chapter (content_id=4)
-- Starting from order_index 25 (after existing 24 items)

INSERT INTO content_items (content_id, title, description, image_url, keywords, order_index) VALUES
(4,'Chú (chi tiết)','Tay phải giống chữ cái ngón tay "N", lòng bàn tay hướng vào trong, đầu ngón tay hướng lên trên, đặt chạm đầu ngón tay vào cằm.','/images/pages/page0109_img01.png','chú,uncle,thân tộc',25),
(4,'Cậu','Tay phải giống chữ cái ngón tay "C", lòng bàn tay hướng sang trái, đặt chạm các đầu ngón tay vào cằm.','/images/pages/page0109_img01.png','cậu,uncle,thân tộc',26),
(4,'Dì','Tay phải nắm, ngón cái và ngón trỏ mở ra, nắm nhẹ vào tai (vị trí đeo khuyên tai). Sau đó đưa nhẹ tay sang bên phải, chuyển tay giống chữ cái ngón tay "D".','/images/pages/page0109_img01.png','dì,aunt,thân tộc',27),
(4,'Chăm bẵm','1. Tay phải giống chữ cái ngón tay "V", lòng bàn tay úp, đầu ngón tay hướng về phía trước, đặt trước cổ, đưa tay về trước. 2. Hai tay khép, lòng bàn tay hướng vào nhau, đặt trước ngực, tay phải đặt trên tay trái, giữ nguyên tay trái, di chuyển tay phải lên – xuống (2 lần).','/images/pages/page0110_img01.png','chăm bẵm,chăm sóc,gia đình',28),
(4,'Dùm bọc','Hai tay mở xoè, lòng bàn tay hướng vào nhau, đầu ngón tay hướng về phía trước, đặt ở hai bên, ngang tầm ngực, đưa đồng thời cả hai tay về giữa ngực, tay phải nằm trên mu bàn tay trái, lòng bàn tay úp.','/images/pages/page0110_img01.png','dùm bọc,bảo bọc,gia đình',29),
(4,'Đồng hồ','Tay trái khép, lòng bàn tay hướng xuống dưới, đầu ngón tay hướng sang phải, đặt trước ngực. Tay phải mở, ngón trỏ và ngón cái tạo thành vòng tròn giống chữ cái ngón tay "O", đặt vào vị trí đeo đồng hồ ở tay trái.','/images/pages/page0110_img01.png','đồng hồ,watch,đồ vật',30),
(4,'Điện thoại','Tay phải giống chữ cái ngón tay "Y", lòng bàn tay hướng sang trái, đầu ngón tay hướng lên trên, đặt áp vào tai phải.','/images/pages/page0110_img01.png','điện thoại,phone,đồ vật',31),
(4,'Ti vi','Hai tay xoè, lòng bàn tay hướng vào trong, đầu ngón tay hướng sang hai bên, đặt gần nhau, trước ngực, đưa lần lượt hai tay lên, xuống ngược nhau (2 lần).','/images/pages/page0111_img01.png','ti vi,television,đồ vật',32),
(4,'Máy vi tính','1. Hai tay giống số tự nhiên "1", lòng bàn tay hướng về phía trước, đầu ngón tay hướng lên trên, đặt gần nhau, trước ngực, đưa đồng thời cả hai tay vẽ một hình chữ nhật. 2. Hai tay xoè hơi khum, lòng bàn tay úp, đầu ngón tay hướng về phía trước, đặt song song trước ngực, cử động các ngón tay của hai tay lên xuống.','/images/pages/page0111_img01.png','máy vi tính,computer,đồ vật',33),
(4,'Đài','1. Tay phải mở, hơi khum lại, lòng bàn tay hướng ra ngoài, đặt ngang tai phải, xoay cổ tay (2 lần). 2. Các ngón tay phải chụm lại sát nhau, đặt trước ngực, di chuyển đầu ngón tay nửa vòng tròn, rồi xoay ngược lại.','/images/pages/page0111_img01.png','đài,radio,đồ vật',34),
(4,'Đèn điện','Các ngón tay phải chụm lại, lòng bàn tay hướng xuống dưới, đặt ngang tầm vai, giữ nguyên cánh tay, mở xoè tay ra (lặp lại 2 lần).','/images/pages/page0111_img01.png','đèn điện,light,đồ vật',35),
(4,'Quạt','Tay trái khép, lòng bàn tay ngửa, đầu ngón tay hướng sang trái, đặt ngang bụng. Tay phải hơi khum lại, lòng bàn tay hướng về phía trước, đặt chạm khuỷu tay lên lòng bàn tay trái, xoay cổ tay sang hai bên (2 lần).','/images/pages/page0112_img01.png','quạt,fan,đồ vật',36),
(4,'Tủ lạnh','1. Hai tay giống số tự nhiên "1", đặt chạm hai đầu ngón tay vào nhau, trước trán, đưa đồng thời cả hai tay vẽ một hình chữ nhật đứng. 2. Tay trái khép, lòng bàn tay hướng lên trên, đặt trước ngực. Tay phải khép, đặt bên trên tay trái, đưa tay mạnh xuống chạm vào giữa lòng bàn tay trái (2 lần).','/images/pages/page0112_img01.png','tủ lạnh,refrigerator,đồ vật',37),
(4,'Giường','1. Hai tay khép, lòng bàn tay hướng xuống dưới, đầu ngón tay hướng về phía trước, đặt song song trước ngực, đưa đồng thời hai tay sang hai bên. 2. Tay phải khép, đặt áp vào má phải.','/images/pages/page0112_img01.png','giường,bed,đồ vật',38),
(4,'Chiếu','1. Hai tay chụm, lòng bàn tay hướng xuống dưới, đầu ngón tay hướng xuống dưới, đặt song song trước ngực, đưa đồng thời hai tay ra ngoài rồi lại vào trong. 2. Hai tay khép, đặt song song trước ngực, đưa đồng thời hai tay sang hai bên.','/images/pages/page0112_img01.png','chiếu,mat,đồ vật',39),
(4,'Chăn','Hai tay khép, hơi khum lại, lòng bàn tay hướng vào trong, đầu ngón tay hướng lên trên, đặt song song trước ngực, đưa đồng thời hai tay lên trên úp vào hai vai.','/images/pages/page0113_img01.png','chăn,blanket,đồ vật',40),
(4,'Gối','1. Tay phải giống chữ cái ngón tay "C", lòng bàn tay hướng về phía trước, đặt trước ngực, đưa tay sang phải. 2. Tay phải khép, đặt áp vào má phải, đầu hơi nghiêng về bên phải.','/images/pages/page0113_img01.png','gối,pillow,đồ vật',41),
(4,'Nồi cơm điện','Hai tay giống chữ cái ngón tay "S", lòng bàn tay hướng vào nhau, đặt lệch nhau trước ngực, đưa tay phải lên trên và sang phải.','/images/pages/page0113_img01.png','nồi cơm điện,rice cooker,đồ vật',42),
(4,'Nồi','1. Hai tay giống số tự nhiên "1", lòng bàn tay úp, đặt chạm hai đầu ngón tay vào nhau, trước ngực, đồng thời hai tay vẽ 1 vòng tròn. 2. Hai tay chụm, lòng bàn tay ngửa, đầu ngón tay hướng sang hai bên, đặt ở hai bên, trước ngực, đưa đồng thời hai tay lên trên.','/images/pages/page0113_img01.png','nồi,pot,đồ vật',43),
(4,'Chảo','1. Hai tay giống số tự nhiên "1", lòng bàn tay úp, đặt chạm hai đầu ngón tay vào nhau, trước ngực, đồng thời hai tay vẽ 1 vòng tròn. 2. Tay phải khép, lòng bàn tay úp, đầu ngón tay hướng về phía trước, lật cổ tay, ngửa bàn tay lên trên.','/images/pages/page0114_img01.png','chảo,pan,đồ vật',44),
(4,'Dao','Hai tay giống số tự nhiên "1", lòng bàn tay úp, đặt vuông góc ngón trỏ tay phải lên ngón trỏ tay trái ở trước ngực, đưa ngón trỏ tay phải tiến lên, lùi xuống (2 lần).','/images/pages/page0114_img01.png','dao,knife,đồ vật',45),
(4,'Bát','Tay phải mở, hơi khum lại, lòng bàn tay ngửa, đầu ngón tay hướng lên trên, đặt trước ngực bên phải.','/images/pages/page0114_img01.png','bát,bowl,đồ vật',46),
(4,'Đĩa','Tay trái khép, lòng bàn tay ngửa, đầu ngón tay chếch sang trái, đặt trước ngực. Tay phải giống số tự nhiên "1", lòng bàn tay úp, đầu ngón tay hướng xuống dưới, đưa ngón trỏ theo hình vòng tròn theo chiều kim đồng hồ trên lòng bàn tay trái.','/images/pages/page0114_img01.png','đĩa,plate,đồ vật',47),
(4,'Thìa','Tay trái khum lại, lòng bàn tay ngửa, đặt trước ngực. Tay phải giống chữ cái ngón tay "X", lòng bàn tay hướng vào trong, đặt chạm vào lòng bàn tay trái và di chuyển lên phía cổ tay trái (2 lần).','/images/pages/page0115_img01.png','thìa,spoon,đồ vật',48),
(4,'Đũa','Tay phải giống chữ cái ngón tay "V", lòng bàn tay hướng vào trong, đầu ngón tay hướng sang trái, hất cổ tay lên, xuống (2 lần).','/images/pages/page0115_img01.png','đũa,chopsticks,đồ vật',49),
(4,'Phích','Tay trái giống chữ cái ngón tay "A", lòng bàn tay hướng vào trong, đặt trước ngực. Tay phải khép, lòng bàn tay úp, đầu ngón tay hướng về trước, đặt phía trên tay trái, đưa tay xuống dưới.','/images/pages/page0115_img01.png','phích,thermos,đồ vật',50),
(4,'Ấm','Tay trái khép, lòng bàn tay ngửa, đặt ngang trước ngực. Tay phải giống chữ cái ngón tay "S", lòng bàn tay hướng sang trái, đầu ngón tay cái hướng lên trên, xoay đầu ngón cái hướng xuống dưới.','/images/pages/page0115_img01.png','ấm,kettle,đồ vật',51),
(4,'Xô','1. Hai tay giống chữ cái ngón tay "L", lòng bàn tay úp, đặt song song trước ngực, đưa đồng thời cả hai tay chéo xuống dưới – vào giữa. 2. Tay phải nắm, lòng bàn tay hướng vào trong, đặt trước bụng, đưa tay lên trên.','/images/pages/page0116_img01.png','xô,bucket,đồ vật',52),
(4,'Chậu','Hai tay khép, hơi khum lại, lòng bàn tay ngửa, đầu ngón tay hướng về phía trước, đặt song song trước bụng, đưa đồng thời hai tay ngang sang bên tạo thành góc vuông rồi đưa lên trên, lòng bàn tay hướng vào nhau.','/images/pages/page0116_img01.png','chậu,basin,đồ vật',53),
(4,'Chổi','Tay trái nắm vào khuỷu tay phải. Tay phải khép, lòng bàn tay hướng sang trái, đầu ngón tay hướng xuống dưới, đưa tay sang phải – sang trái (2 lần).','/images/pages/page0116_img01.png','chổi,broom,đồ vật',54),
(4,'Cây lau nhà','Hai tay nắm, lòng bàn tay hướng vào nhau, đặt trước ngực, tay trái đặt trước, tay phải đặt sau, đưa đồng thời cả hai tay về phía trước (2 lần).','/images/pages/page0116_img01.png','cây lau nhà,mop,đồ vật',55);
