USE vsl_learning;
-- Seed Nghe nghiep FULL from PDF p.120-128
-- Replace inaccurate items & add missing ones
-- First fix existing items with correct descriptions from PDF
UPDATE content_items SET title='Cô giáo', description='1. Tay phải nắm, ngón cái và ngón trỏ mở ra, nắm nhẹ vào tai (vị trí đeo khuyên tai). 2. Tay phải giống số tự nhiên "1", lòng bàn tay hướng sang trái, đầu ngón tay hướng lên trên, đặt bên phải, ngang tầm mặt, đưa tay sang phải đồng thời gập cổ tay ra - vào.', image_url='/images/pages/page_0120.png' WHERE content_id=5 AND title='Giáo viên';

UPDATE content_items SET description='Tay phải nắm, ngón cái và ngón trỏ tay phải cong lại giống chữ C, lòng bàn tay hướng vào trong, đặt chạm vào ngực trái, đưa nhẹ tay sang phải.', image_url='/images/pages/page_0120.png' WHERE content_id=5 AND title='Công nhân';

UPDATE content_items SET description='1. Tay phải giống chữ S, lòng bàn tay hướng vào trong, đặt gần ngực trái, đưa tay sang ngực phải. 2. Ngón cái và ngón trỏ của hai tay chạm vào nhau, các ngón khác nắm lại, lòng bàn tay úp, đặt trước ngực, giữ nguyên tay trái, đưa tay phải xuống dưới (2 lần).', image_url='/images/pages/page_0120.png' WHERE content_id=5 AND title='Nông dân';

UPDATE content_items SET description='Tay phải giống số tự nhiên "1", lòng bàn tay úp, đầu ngón tay hướng sang trái, đặt sát giữa trán, đưa tay theo hình dấu "+".', image_url='/images/pages/page_0120.png' WHERE content_id=5 AND title='Bác sĩ';

UPDATE content_items SET description='Tay phải giống số tự nhiên "1", lòng bàn tay hướng vào trong, đầu ngón tay hướng vào trong, đưa chạm đầu ngón trỏ vào bắp tay trái.', image_url='/images/pages/page_0121.png' WHERE content_id=5 AND title='Y tá';

UPDATE content_items SET description='Tay phải giống chữ U, lòng bàn tay hướng sang trái, đặt chạm vào trán bên phải, đưa tay xuống chạm vào vai phải.', image_url='/images/pages/page_0121.png' WHERE content_id=5 AND title='Bộ đội';

UPDATE content_items SET description='1+2. Tay phải giống chữ C, lòng bàn tay hướng sang trái, đặt chạm vào giữa trán, sau đó thay đổi tay giống chữ A.', image_url='/images/pages/page_0121.png' WHERE content_id=5 AND title='Công an';

UPDATE content_items SET description='1. Tay trái khép, lòng bàn tay úp, đầu ngón tay hướng sang phải, đặt trước ngực. Tay phải khép, lòng bàn tay hướng sang trái, đầu ngón tay hướng về phía trước, đặt chạm trên mu bàn tay trái, đưa tay phải lên, xuống (2 lần). 2. Hai tay giống chữ C, lòng bàn tay hướng vào nhau, đặt trước hai mắt, đưa tay lên - xuống về phía trước (2 lần).', image_url='/images/pages/page_0121.png' WHERE content_id=5 AND title='Thợ xây';

UPDATE content_items SET description='1+2. Tay phải giống chữ K, lòng bàn tay úp, đầu ngón tay hướng sang trái, đặt trước ngực, sau đó chuyển hình dạng bàn tay giống chữ S.', image_url='/images/pages/page_0124.png' WHERE content_id=5 AND title='Kĩ sư';

-- Add missing items for Nghe nghiep
INSERT INTO content_items (content_id, title, description, image_url, keywords, order_index) VALUES
(5,'Thợ may','1. Tay phải giống chữ S, lòng bàn tay hướng vào trong, đặt gần ngực trái, đưa tay sang ngực phải. 2. Hai tay khép, lòng bàn tay úp, đầu ngón tay hướng về trước, đặt trước ngực, tay trái ở ngoài, tay phải ở trong, gập đồng thời hai cổ tay lên - xuống (2 lần).','/images/pages/page_0122.png','thợ may,nghề nghiệp',13),
(5,'Thợ mộc','1. Tay phải giống chữ S, lòng bàn tay hướng vào trong, đặt gần ngực trái, đưa tay sang ngực phải. 2. Hai tay nắm, lòng bàn tay úp, đặt trước ngực, tay trái đặt ngoài, tay phải đặt trong, đưa hai tay đồng thời ra - vào (2 lần).','/images/pages/page_0122.png','thợ mộc,nghề nghiệp',14),
(5,'Thợ lặn','1. Tay phải giống chữ S, lòng bàn tay hướng vào trong, đặt gần ngực trái, đưa tay sang ngực phải. 2. Tay trái xoè, hơi khum lại, lòng bàn tay hướng vào trong, đặt trước mặt. Tay phải giống chữ Đ, lòng bàn tay hướng ra ngoài, gập cổ tay lên - xuống (2 lần).','/images/pages/page_0122.png','thợ lặn,nghề nghiệp',15),
(5,'Thợ xe','1. Tay phải giống chữ S, lòng bàn tay hướng vào trong, đặt gần ngực trái, đưa tay sang ngực phải. 2. Hai tay nắm, lòng bàn tay hướng vào nhau, đặt trước ngực, tay trái đặt ngoài, tay phải đặt trong, đưa hai tay đồng thời ra - vào (2 lần).','/images/pages/page_0122.png','thợ xe,nghề nghiệp',16),
(5,'Thợ hàn','1. Tay phải giống chữ S, lòng bàn tay hướng vào trong, đặt gần ngực trái, đưa tay sang ngực phải. 2. Tay trái xoè, hơi khum lại, lòng bàn tay hướng vào trong, đặt trước mặt. Tay phải giống chữ Đ, lòng bàn tay hướng ra ngoài, gập cổ tay lên - xuống (2 lần).','/images/pages/page_0123.png','thợ hàn,nghề nghiệp',17),
(5,'Thợ mổ','1. Tay phải chụm, lòng bàn tay hướng về trước, đặt chạm vào giữa trán, giữ nguyên cánh tay, mở xoè các ngón tay ra. 2. Tay trái khép, hơi khum lại, lòng bàn tay úp, đầu ngón tay hướng sang phải, đặt trước ngực. Tay phải khép, khum lại, lòng bàn tay úp, đặt chạm mu bàn tay vào lòng bàn tay trái, lắc cổ tay qua - lại (2 lần).','/images/pages/page_0123.png','thợ mổ,nghề nghiệp',18),
(5,'Người bán hàng','1. Tay phải giống chữ S, lòng bàn tay hướng vào trong, đặt gần ngực trái, đưa tay sang ngực phải. 2. Hai tay giống chữ O, lòng bàn tay ngửa, đặt song song trước ngực, đưa đồng thời cả hai tay về trước và sang hai bên đồng thời mở xoè tay ra.','/images/pages/page_0123.png','người bán hàng,nghề nghiệp',19),
(5,'Công việc','1. Hai tay nắm, lòng bàn tay hướng vào trong, đặt trước ngực, tay phải đặt bên trên tay trái, đưa tay phải xuống dưới chạm vào tay trái (2 lần). 2. Hai tay khép, lòng bàn tay úp, đầu ngón tay hướng về phía trước, đặt song song trước ngực, đưa nhẹ đồng thời cả hai tay lên - xuống 2-3 lần và sang phải.','/images/pages/page_0123.png','công việc,nghề nghiệp',20),
(5,'Thợ thêu','1. Tay phải giống chữ S, lòng bàn tay hướng vào trong, đặt gần ngực trái, đưa tay sang ngực phải. 2+3. Hai tay mở xoè, khum lại, đầu ngón cái và ngón trỏ chạm vào nhau, lòng bàn tay úp, đầu ngón tay hướng về phía trước, đặt gần nhau, trước ngực, giữ nguyên tay trái, đưa tay phải lên trên và sang trái.','/images/pages/page_0124.png','thợ thêu,nghề nghiệp',21),
(5,'Người','Tay phải giống chữ S, lòng bàn tay hướng vào trong, đặt gần ngực trái, đưa tay sang ngực phải.','/images/pages/page_0124.png','người,nghề nghiệp',22),
(5,'Dạy học','1+2. Tay phải giống chữ O, lòng bàn tay hướng sang trái, đặt chạm vào giữa trán, đưa tay về phía trước đồng thời mở xoè tay ra, lòng bàn tay úp, đầu ngón tay hướng về phía trước (lặp lại 2 lần).','/images/pages/page_0124.png','dạy học,nghề nghiệp',23),
(5,'Súng','Tay phải giống chữ U, lòng bàn tay hướng sang trái, đầu ngón tay hướng về phía trước, đặt trước ngực phải, đầu ngón tay hướng ra ngoài, di chuyển tay ra - vào (2 lần).','/images/pages/page_0125.png','súng,dụng cụ',24),
(5,'Còi','Tay phải giống chữ U, lòng bàn tay hướng vào trong, đặt lên môi, sau đó xoay cổ tay phải theo hình vòng cung hướng ra ngoài, miệng hình tròn.','/images/pages/page_0125.png','còi,dụng cụ',25),
(5,'Gạch','1. Hai bàn tay hơi khum lại, ngón cái mở ra, lòng bàn tay hướng vào nhau, đặt chạm các đầu ngón tay vào nhau, đưa đồng thời hai tay sang hai bên. 2. Tay phải giống số 1, lòng bàn tay hướng sang trái, đặt chạm ngón tay trỏ vào miệng, đưa tay xuống.','/images/pages/page_0125.png','gạch,vật liệu',26),
(5,'Búa','Hai tay nắm, lòng bàn tay hướng vào nhau, đặt hai bên trước ngực, tay trái thấp, tay phải cao, đưa tay phải chạm mạnh vào tay trái (2 lần).','/images/pages/page_0125.png','búa,dụng cụ',27),
(5,'Máy khâu','1. Tay phải mở, hơi khum lại, lòng bàn tay hướng sang bên trái, đặt trước ngực, xoay cổ tay qua - lại. 2. Hai tay khép, lòng bàn tay úp, đầu ngón tay hướng về trước, đặt trước ngực, tay trái ở ngoài, tay phải ở trong, gập đồng thời hai cổ tay lên - xuống (2 lần).','/images/pages/page_0126.png','máy khâu,dụng cụ',28),
(5,'Kim','Tay phải nắm, đầu ngón cái và ngón trỏ chạm vào nhau, lòng bàn tay hướng sang trái, đầu ngón tay hướng sang trái, đặt trước ngực phải, đưa tay sang trái và gập cổ tay ra - vào.','/images/pages/page_0126.png','kim,dụng cụ',29),
(5,'Chỉ','Hai tay giống chữ I, lòng bàn tay hướng vào trong, đầu ngón tay hướng sang hai bên, đặt gần nhau, trước ngực, đưa đồng thời hai tay sang hai bên.','/images/pages/page_0126.png','chỉ,dụng cụ',30),
(5,'Thước dây','1. Tay trái khép, lòng bàn tay úp, đầu ngón tay hướng sang phải, đặt trước ngực. Tay phải khép, lòng bàn tay hướng vào trong, đầu ngón tay hướng xuống dưới, đặt chạm vào khuỷu tay trái, đưa tay đến cổ tay trái. 2. Hai tay nắm, ngón cái và ngón trỏ chụm lại, lòng bàn tay hướng vào nhau, đặt trước ngực, đưa đồng thời hai tay sang hai bên.','/images/pages/page_0126.png','thước dây,dụng cụ',31),
(5,'Cưa','Tay trái khép, lòng bàn tay úp, đầu ngón tay hướng sang phải, đặt trước ngực. Tay phải khép, lòng bàn tay hướng sang trái, đầu ngón tay hướng về phía trước, đặt chạm lên mu bàn tay trái, di chuyển tiến lên, lùi lại trên mu bàn tay trái (2 lần).','/images/pages/page_0127.png','cưa,dụng cụ',32),
(5,'Máy cày','1. Tay phải mở, hơi khum lại, lòng bàn tay hướng sang bên trái, đặt trước ngực, xoay cổ tay qua - lại. 2. Hai tay giống chữ Y, lòng bàn tay úp, hai ngón cái chạm nhau, đặt trước ngực, đưa đồng thời hai tay về phía trước.','/images/pages/page_0127.png','máy cày,nông nghiệp',33),
(5,'Cày bừa','Tay trái khép, lòng bàn tay ngửa, đầu ngón tay hướng về phía trước, đặt trước ngực. Tay phải giống chữ Y, lòng bàn tay hướng sang trái, đặt ngón út chạm vào lòng bàn tay trái, đưa tay lên phía trước, đồng thời lắc cổ tay.','/images/pages/page_0127.png','cày bừa,nông nghiệp',34),
(5,'Cấy lúa','1+2. Hai tay giống số 1, lòng bàn tay hướng vào trong, đầu ngón tay hướng xuống dưới, đưa lần lượt hai tay lên - xuống ngược chiều nhau (2 lần).','/images/pages/page_0127.png','cấy lúa,nông nghiệp',35),
(5,'Máy tuốt lúa','Tay trái mở, hơi khum lại, lòng bàn tay hướng sang phải, đặt trước ngực, xoay cổ tay qua - lại (2 lần). Tay phải giống số 4, lòng bàn tay hướng ra ngoài, đặt ngang vai phải, đưa tay phải úp lên tay trái (2 lần).','/images/pages/page_0128.png','máy tuốt lúa,nông nghiệp',36),
(5,'Tiêm thuốc','Tay phải giống chữ I, lòng bàn tay hướng vào trong, đặt chạm đầu ngón tay vào bắp tay trái.','/images/pages/page_0128.png','tiêm thuốc,y tế',37);
